version: "3"

volumes:
  hddacme:
  hddcanon:
  hddletsencrypt:
  hddrestui:

networks:
  default:

services:
  certbot:
    image: certbot/certbot:latest
    volumes:
      - hddletsencrypt:/etc/letsencrypt
      - hddacme:/tmp/certbot-acme
      - ./certbot/cli.ini:/etc/letsencrypt/cli.ini
      - ./certbot/fake-certs.sh:/fake-certs.sh
      - ./certbot/real-certs.sh:/real-certs.sh
    environment:
      - EMAIL=datachile@datawheel.us

  restui:
    build: https://github.com/Datawheel/mondrian-rest-ui.git#master
    volumes:
      - hddrestui:/app/src/build
    environment:
      - REACT_APP_API_URL=https://chilecube.datachile.io
    command: yarn run build

  db:
    image: "postgres:latest"
    volumes:
      - ./db/postgresql.conf:/etc/postgresql.conf
      - ./db/init.d:/docker-entrypoint-initdb.d
      - /datastore/postgres:/var/lib/postgresql/data
      - /datastore/dumps:/app/dumps
      - /datastore/shared:/app/shared
    environment:
      - POSTGRES_PASSWORD="please set a password"
    ports:
      - "5432:5432"
    restart: unless-stopped
    command: postgres -c config_file=/etc/postgresql.conf

  mondrian:
    build: https://github.com/datachile/datachile-mondrian.git#master
    depends_on:
      - db
    volumes:
      - ./mondrian/config.yaml:/mondrian-rest/config.yaml:ro
      - ./mondrian/schema.xml:/mondrian-rest/schema.xml:ro
      - /datastore/shared:/app/shared
    environment:
      - MONDRIAN_REST_CONF=/mondrian-rest/config.yaml
    expose:
      - "9292"
    restart: unless-stopped

  canon:
    build: https://github.com/datachile/datachile.git#staging
    depends_on:
      - mondrian
    volumes:
      - hddcanon:/datachile/static
      - /datastore/shared:/app/shared
    environment:
      - NODE_ENV=production
      - APP_HOME=/datachile
      - ROOT=/datachile
      - CANON_API=https://chilecube.datachile.io
      - CANON_CONST_API=https://chilecube.datachile.io
      - CANON_GOOGLE_ANALYTICS=UA-109603240-1
      - CANON_LANGUAGE_DEFAULT=es
      - CANON_LANGUAGES=es,en
      - CANON_LOGICLAYER_CUBE=http://mondrian:9292/
      - CANON_LOGICLAYER_LOGGING=true
      - CANON_PORT=4444
    expose:
      - "4444"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    depends_on:
      - canon
      - mondrian
      - restui
    volumes:
      - hddacme:/tmp/certbot-acme
      - hddcanon:/app/canon-static:ro
      - hddletsencrypt:/etc/letsencrypt
      - hddrestui:/app/restui
      - /datastore/cache-canon:/ncache/canon
      - /datastore/cache-mondrian:/ncache/mondrian
      - /datastore/public:/app/public
      - /datastore/shared:/app/shared
      - ./nginx/hosts:/etc/nginx/conf.d
      - ./nginx/snippets:/etc/nginx/snippets
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    logging:
      driver: gcplogs
